name: Build WowUp Electron Windows
on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  build:
    name: Build
    runs-on: windows-latest 
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'wowup-electron/package-lock.json'

      - run: npm ci
        working-directory: wowup-electron

      - name: Build Windows App
        working-directory: wowup-electron
        run: npm run electron:publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
